### ISSUE TITLE
Video header samples

### ISSUE THREAD

**Issue by csimmons44** [OPLBPO/opl_storybook#1]
Found some good stock videos for the video header. Rosehip in snow for the 1st story was the winner, teapot #2.
 
I can buy one of these and I believe the iStock license allows you to upload your derivative to Youtube, but we probably would have to set the privacy to ‘Unlisted’.
 
http://www.istockphoto.com/ca/video/hd-rosehip-gm461560428-55737374?st=_p_rosehips%20winter
 
http://www.istockphoto.com/ca/video/hd-steaming-teapot-gm472834333-16340513?st=_p_winter%20kitchen
 
Another Rosehip option:
 
http://www.istockphoto.com/ca/video/hd-rosehip-gm461262680-55481538?st=_p_winter

**Comment by csimmons44** [comment]
@wendywarren  which resolution would be best for the video header? 

![image](https://cloud.githubusercontent.com/assets/4601731/21618230/e62cb91c-d1b7-11e6-8630-ad0883e71aad.png)

**Comment by wendywarren** [comment]
Hi @csimmons44 ! The one you'll want to go with is HD 1920x1080. :)

Do you know if they will want to place video in between regions? For an example of what I'm talking about, visit this site http://couleecreative.com/ and scroll to the bottom.

**Comment by wendywarren** [comment]
1920x1080 would ensure it's crisp on large monitors but I guess we should take into consideration the file size. I downloaded an example of an iStock short video (640x360 H.264) with the logo overtop and it was just over 2mb. I can't imagine the HD will exceed a reasonable file size being that clip will be about 10 seconds.

**Comment by csimmons44** [comment]
Hi Wendy, I shared the video via Dropbox so let me know if you get it ok.

**Comment by wendywarren** [comment]
@csimmons44 I downloaded the video from dropbox. It's quite a large file size. Is there a way to see the files sizes attached to each video size before downloading? When I looked online, sites suggested using this format but I didn't expect the size to be so large. I can look into compressing without losing too much quality.

**Comment by csimmons44** [comment]
I can download the smaller video for free, would Jpeg or H.264 be better?

**Comment by wendywarren** [comment]
From what I read, h.264.

**Comment by csimmons44** [comment]
Ok, sent. It's quite a bit smaller file.

**Comment by wendywarren** [comment]
Thanks! Got it!
