### ISSUE TITLE
Content for January

### ISSUE THREAD

**Issue by wendywarren** [OPLBPO/opl_storybook#14]
Happy New Year @csimmons44 ! I was wondering if you could forward me the content that will be included for the January chapter of the Food Literacy storybook. I believe this includes:

- Main title of chapter  
- short video on loop at the top
- article
- youTube videos
- podcasts
- images (separate or part of a gallery)
- collections of books, recipes
- Twitter, Facebook, Instagram accounts that the feature should use to share the page 
- bg image behind credits at the bottom of page

Let me know if I've missed a content type in the list above. If you could zip up two folders - one for French and one for English, that would be great. 

I wanted to try placing everything in on the page as you would and create a step by step guide using the material. In future months you would refer to the guide to create the storybook pages. Does that sound good to you? I'd like to have this to you for Friday to review and start testing / playing around with.

In the future, which team at the library will be responsible for adding the content?

**Comment by csimmons44** [comment]
Sounds great Wendy, I'll gather that for you. In the future, Sherry will be adding the content but we'll be involved to help out. Happy New Years, Chris

**Comment by crawleyde** [comment]
Hi @wendywarren  -- I've been helping with some sound files. I think we'll need to publish transcripts along with them. (I think that just means adding a 'transcript' link beside the player to open the transcript text. Doesn't need to be too fancy.) I'm not sure if we scoped that before.

**Comment by wendywarren** [comment]
@crawleyde - I don't think we discussed much about the transcript text but your suggestion of having text that opens up makes sense to me. I can place it in an overlay for the user to read.

**Comment by csimmons44** [comment]
Recipe and event view sent as Feature. I can put up the new Instagram widget once its on our site.

**Comment by crawleyde** [comment]
The recipe content type should be available later this afternoon. I pasted the view export into a separate ticket.

**Comment by wendywarren** [comment]
@crawleyde I imported the view but I can't seem to find it within the list of available content within panels. I'm wondering if I should edit the view to be a content pane and list it under Storybook.

**Comment by crawleyde** [comment]
Thanks, that sounds like a good idea. I try to make content panes these days. Is there an existing feature for food literacy/storybook. I don't want to create a new feature just to export the recipe content type. Perhaps I need to though.

**Comment by wendywarren** [comment]
There is! :) The feature is OPL Storybook and saved within the module opl_storybook. Since I have to export all of my changes today (including the events view), would you like to export that one content type separately and send it to me? I can include it with my changes later this afternoon.

**Comment by crawleyde** [comment]
Yes I'll do that. (Can you give me a quick hint of how to export a content type without using features?)

**Comment by wendywarren** [comment]
I think you can go to admin/structure/types/export and select just that one content type. Let me know how that goes. I may be wrong.

**Comment by crawleyde** [comment]
Sorry -- found it!

**Comment by wendywarren** [comment]
@csimmons44 @crawleyde  - I'm looking into the event view this morning. For some reason I don't see any events at the moment on opl.cflabs. I'll send you an update later to let you know everything is displaying properly.

As for the recipe content, how should this be displayed within the page? Is there a preferred layout or number of recipes that should display? Should it include the picture and title with a link to the full node? We hadn't really discussed recipes all that much.

**Comment by csimmons44** [comment]
Probably that opl.cflabs database doesn't have the series term or any events with that series. Should we include the series taxonomy and the nodes in the feature or just do that manually on that site?

**Comment by crawleyde** [comment]
For the recipe node layout, I was basically thinking of something resembling epicurious, with a bulleted list of ingredients, followed by the instructions. Perhaps the search result or teaser layout could be repurposed for listing them. I'm under the impression there may just be one per month to start, but probably more as more are contributed by the public.
![spaghetti](https://cloud.githubusercontent.com/assets/2026835/22337642/792e066e-e3b3-11e6-8db9-2f8db88fb2eb.png)

**Comment by wendywarren** [comment]
@csimmons44 - Thanks Chris! I wasn't sure if we were displaying the full recipe on the page or just the link but for now I will create a storybook layout to display single recipes and then we can revisit how to deal with multiple recipes per month, once this month has went live if that's ok with you.

**Comment by csimmons44** [comment]
Sounds good, thanks.
