### ISSUE TITLE
OPL Logo is a bit too narrow on storybook template

### ISSUE THREAD

**Issue by crawleyde** [OPLBPO/opl_storybook#22]
Our comms dept. will definitely flag this, so I'll note it first.

https://stage2.biblioottawalibrary.ca/en/storybook/food literacy/comfort food

**Comment by wendywarren** [comment]
@crawleyde Would you mind attaching a screen shot of the logo when you get a chance. It's displaying properly on my screens.

**Comment by crawleyde** [comment]
Firefox on my Mac:
<img width="1437" alt="screen shot 2017-02-03 at 4 13 56 pm" src="https://cloud.githubusercontent.com/assets/2026835/22608688/f4d1b27e-ea2b-11e6-962c-9222e2a92207.png">
