### ISSUE TITLE
aside styling affects all right-hand sidebars

### ISSUE THREAD

**Issue by crawleyde** [OPLBPO/opl_storybook#23]
I notice that in _storybook.scss this is affecting all right-hand asides across the site:
```
/* =Section Aside */
aside {
  width: 100%;
  background-color: #f2f2f2;
  padding: 0 30px;
}
```
@wendywarren can you set it to affect only the storybook content? (Perhaps putting it under #oplfla-chapters?)

**Comment by wendywarren** [comment]
Oh geez. Sorry! I thought I put it within ' .storybook' I'll fix that and include with what I'm committing now for the first letter of the first paragraph.
