### ISSUE TITLE
Storybook standalone image not displaying

### ISSUE THREAD

**Issue by crawleyde** [OPLBPO/opl_storybook#26]
@wendywarren , I added node 48137 on prod (a storybook stand-alone image) to the storybook panel here (https://biblioottawalibrary.ca/en/admin/structure/pages/nojs/operation/page-storybook/handlers/page_storybook__panel/content) but it's not displaying. The image should be the first item in aside #2. Would you mind having a look? Many thanks.

**Comment by wendywarren** [comment]
Hi @crawleyde It ended up being that I instructed you to enable the Storybook Single Image panelized entity when the default for that doesn't have a display mode. Sorry about that. I disabled it and now the image shows up on the page. The images are set to 100% of it's original size but you can decrease the size by applying a width in panel styles.

**Comment by crawleyde** [comment]
Great, thanks @wendywarren .
