### ISSUE TITLE
.svg images not displaying

### ISSUE THREAD

**Issue by crawleyde** [OPLBPO/opl_storybook#27]
I think the jquery.fitvids.js file is interfering with our event category .svg images. Line 63 of that file inserts the .fluid-width-video-wrapper class for any object embed, which are .svgs are. When I remove that class in Firebug, the .svgs reappear again.
```
        if (this.tagName.toLowerCase() === 'embed' && $this.parent('object').length || $this.parent('.fluid-width-video-wrapper').length) { return; }
```
I'm not sure how to limit that js file include to just the storybook content. Is that possible?

**Comment by wendywarren** [comment]
@crawleyde Let me ask Mat about that and get back to you.

**Comment by wendywarren** [comment]
@minorOffense Is there a way to limit the loading of a contrib module's js only on certain pages?

**Comment by wendywarren** [comment]
Hey @crawleyde! Can you replace body with body.storybook on this page:
admin/config/media/fitvids

Reminder: Clear the js cache.

Hopefully that will work for you. Let us know if it fixes the problem. :)

**Comment by crawleyde** [comment]
Thanks, that worked great.

**Comment by minorOffense** [comment]
@wendywarren we exported the conf change right?

**Comment by wendywarren** [comment]
@minorOffense No I don't believe so but will do it this morning.
