### ISSUE TITLE
Custom storybook pane styling for 1/3 left is showing as 2/3

### ISSUE THREAD

**Issue by crawleyde** [OPLBPO/opl_storybook#28]
Hardly a major issue, but I'm not sure where to update the panel/template settings. When I set an item to have 1/3 left positioning it's showing as taking up 2/3 of the page instead.

**Comment by wendywarren** [comment]
@crawleyde So sorry about that! It would be within the _storybook.scss file. Let me find exactly where it should be adjusted. Would you like me to update the theme and submit a merge request to you?

**Comment by crawleyde** [comment]
Sure that would be great, thanks!

**Comment by wendywarren** [comment]
@crawleyde Merge request sent :)
