### ISSUE TITLE
Create wireframe of sample chapter layout

### ISSUE THREAD

**Issue by wendywarren** [OPLBPO/opl_storybook#4]

**Comment by wendywarren** [comment]
Sample with nav closed:

![quick mockup-01](https://cloud.githubusercontent.com/assets/12865609/20635598/314ba84e-b32d-11e6-9c39-5a571a0a0d6e.jpg)



Sample with nav expanded, listing all chapters:

![quick mockup-02](https://cloud.githubusercontent.com/assets/12865609/20635599/33ab567a-b32d-11e6-86fd-9b24637f99a4.jpg)

**Comment by csimmons44** [comment]
Hi Wendy, would you like feedback on this or just anything in UXPin?

**Comment by wendywarren** [comment]
@csimmons44 Sure! Probably a good idea to confirm our sample layout is on the right track. I added the two images on UXPin. You can access them here:

Nav collapsed - https://collaborate.uxpin.com/5581f4c92db0baf1a92d2f3eabfbf4c4ca372f20#/pages/64628543
Nav expanded - https://collaborate.uxpin.com/5581f4c92db0baf1a92d2f3eabfbf4c4ca372f20#/pages/64628551

**Comment by wendywarren** [comment]
@csimmons44 I have a couple questions as I start building the pages for the project. Do you know if there will be multiple podcasts and/or youtube links? Makes it easier to figure out layout if I know there will be on average 1, 2 or 6 of each per month.

My plan for youtube was to have a text field where the user (when creating the page) would paste the link to the youtube video and for podcasts, they would upload an mp3 file and I'll link it to a custom audio player I'm creating with a play/pause button, progress bar and time of podcast.

**Comment by csimmons44** [comment]
Sorry for the delay, missed this one. I think typically there will be 1 podcast and/or 1 youtube video per story but you may want to build in the ability to add a second. Currently we use the Media module and the Media: Youtube module so there is an existing upload field: field_media_file_upload, we could reuse that field.

https://biblioottawalibrary.ca/en/admin/structure/types/manage/blog/fields/field_media_file_upload

**Comment by wendywarren** [comment]
Not a problem at all! :)

I have created a sample layout that I can throw on cflabs this morning for you to review. All of the markup have been placed in the template file so next step will be building out the layout and have Melissa add styling but just wanted to make sure we were on the right track. 

My plan was to use content types with each node having the option to select which month this content is associated with. Then in pages you can organize the content as you wish. Each month would have it's own page.

I'll message you in a bit with a link for your review. Thanks!

**Comment by wendywarren** [comment]
@csimmons44  Here's where I'm at so far. 

http://opl.cflabs.ca/storybook

The nav (view more stories) will be smoother and the second set of three images will be replaced with an example of related collections or events. 

Let me know if you have any feedback. I'm just starting the process of creating custom content types.

**Comment by wendywarren** [comment]
When it comes to adding the collections and / or events as an aside in the grey section, I was going to list 5 or 6 across with image and title. Does that sound good?

**Comment by csimmons44** [comment]
Wow, that looks great! For the collections that sounds good, could probably use either the same style as our homepage or the /collections carousels. For events, I think there may be just one so perhaps a card like our homepage with the program type?

**Comment by csimmons44** [comment]
One thing to add to the header would be a link back to our website.

**Comment by csimmons44** [comment]
Hi Wendy, we were discussing the app today in the context of stories other than Food Literacy. Perhaps the View more stories button could be a dropdown menu to to display other sets of stories than Food Literacy?

In any case, it'd be good to consider that now if you have other ideas of how we could present that. And perhaps we have a taxonomy on the story node type to divide them into different sets.

**Comment by wendywarren** [comment]
@csimmons44 We can definitely come up with a few ideas to handle multiple storybooks. Melissa was going to update the header area this morning to include logo, link to OPL site, EN/FR and buttons to different stories. Would the stories have their own colour scheme or will they all be related to 'a la carte'?

Speaking of 'a la carte', I can't remember if you had sent the horizontal logo our way. Would you mind sending it again if you have already? Thanks!
