### ISSUE TITLE
Top nav / share bar

### ISSUE THREAD

**Issue by wendywarren** [OPLBPO/opl_storybook#7]
Ideas go here...

**Comment by wendywarren** [comment]
Top nav scrolls up with rest of page and once it gets to about 60px scroll mark the share bar will appear like this:

![screen shot 2016-12-15 at 11 17 39 am](https://cloud.githubusercontent.com/assets/12865609/21232108/8267d834-c2b8-11e6-99cf-f4fe7db21ec1.png)

**Comment by wendywarren** [comment]
Hi @csimmons44 @crawleyde !

I've added the images to show up next to the book in the menu at the top of the page but cannot get the site to allow svg uploads on cflabs. I must be missing something. How did you set it up on your system to allow svg?

**Comment by crawleyde** [comment]
I think we had to switch to the media module package if you're not using that. From there I added .svg as an uploadable format. And we had to switch the image renderer to imagemagick I think.

**Comment by wendywarren** [comment]
Thanks @crawleyde ! I ended up just changing the widget from image to media browser and that allowed me to upload the svg. Perfect!

**Comment by crawleyde** [comment]
OK, great.
